server {
    listen       80;
    listen  [::]:80;
    server_name  _;
    root   /usr/share/nginx/html;
    index  index.html;

    location = /zergx-app-release.apk {
        default_type application/vnd.android.package-archive;
        add_header Content-Disposition 'attachment; filename="zergx-app-release.apk"';
    }

    location / {
        autoindex on;
    }
}